### ISSUE TITLE
Xelatex vs pdflatex

### ISSUE THREAD

**Issue by vishvish** [ukulele/songbook#1]
Hi all, especially @icarusfall 

I'm just updating things for 2023, looks like Maven is moaning about the typesetting engine...

Is everyone ok with using xelatex vs pdflatex?

**Comment by icarusfall** [comment]
Don't think it's a problem with me!

**Comment by vishvish** [comment]
Not going to fix this, have standardized on PDFLatex now as build is being done in Github.
