### ISSUE TITLE
Build songbook and publish a PDF right here

### ISSUE THREAD

**Issue by vishvish** [ukulele/songbook#2]
Would it help if I created a pipeline here to build the songbook on every change and create a release? @icarusfall?

**Comment by icarusfall** [comment]
I think so. I keep meaning to add some more songs. I've got a long list of
stuff to add

**Comment by gwyndaf** [comment]
I'll abstain as I don't really have time to master LaTeX. However, it seems there's a LaTeX backend for my ChrordPro approach, which is maybe something to explore at some future point, once I've, erm, had time to master LaTeX!

@icarusfall I don't think I've got you on my songbook circulation - would you like to be added?

**Comment by icarusfall** [comment]
Definitely! I love a songbook!

**Comment by vishvish** [comment]
@gwyndaf it's exactly because of that - I figured that everyone can benefit from the PDF being auto-published when songs are added, and it's easy to merge PDFs together. I'll get on with this ASAP.

**Comment by gwyndaf** [comment]
No rush on my account. My current needs are pretty extensive, and I've already got design, standards and process that serve them well enough.

**Comment by vishvish** [comment]
Well that took a chunk out of my evening, but off for a couple of days so no real choice.

The Songbook is now building on Github and the finished PDF appears as a release here:

https://github.com/ukulele/songbook/releases

Releases also appear on the right side of the Songbook Github page. Each new version is automatically tagged and versioned.

Ok - so @icarusfall - I had to a make a load of corrections and fixed to get the thing to build. 

1. there were some spurious characters that the build didn't like, like 1/4 sized spaces. Finally figured that out and replaced with normal spaced.
2. there were some non-standard hash/sharp marks, I replaced them with # marks.
3. there were chords missing, which are all defined in the root `songbook.tex` file. I don't expect people to add them, but it's interesting to learn how.
4. I have changed the default font to Palatino, looks better.
5. I have made the chord fret diagrams slightly smaller so it's easier to fit them on a page when there's load - Nellie The Elephant???
6. I've also got a new chord or two further up the fretboard with numbers marking the start fret on the diagram.

So all good in the hood! @gwyndaf no need to learn Latex although TBH, each song is barely Latex and fairly easy to parse, especially for a hacker of your renown.

I will pop in some more tunes when I can. Thanks everyone!

**Comment by icarusfall** [comment]
Yes, I've been trying to add chords to the .tex file. Sorry if I missed
some. Like you say, it's pretty self explanatory how they work.

**Comment by vishvish** [comment]
@icarusfall They're a bit persnickety as I've been learning when going beyond the basic and intermediate chords, but hopefully now there's enough examples and some kinds of naming convention to boot. The mans are case-sensitive, I have just discovered.

**Comment by vishvish** [comment]
Essentially the pipeline build and release will now fail if there's an error or missing chord or something so that will help us keep the thing working.
